version: "3.8"

services:
  db:
    image: postgres:15
    container_name: documentation-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documentation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: documentation-keycloak
    restart: unless-stopped
    # command: ["/bin/sh", "-c", "sleep 10 && start-dev --http-host=0.0.0.0"]
    command: ["start-dev", "--http-host=0.0.0.0"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/documentation_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
