export const validAttributes = {
  id: "ID",
  document: "CPF",
  ddd: "DDD",
  email: "E-mail",
  name: "Nome",
  social_name: "Nome Social",
  gender: "Sexo",
  phone: "Telefone",
  birth_date: "Data de Nascimento",
  initial_date: "Data Inicial",
  final_date: "Data Final",
  zip_code: "CEP",
  city: "Cidade",
  state: "Estado",
  address: "Endereço",
  complement: "Complemento",
  attachment: "Lista de Arquivos",
  page: "Página",
  per_page: "Itens por Página",
  total: "Total de registros",
  total_pages: "Total de páginas",
  current_page: "Página atual",
  action: "Ação",
  channel: "Canal",
  company: "Empresa",
  message: "Mensagem",
  value: "Valor",
  amount: "Quantidade",
  protocol: "Protocolo",
  description: "Descrição",
  reason: "Motivo",
  sub_reason: "Sub Motivo",
  type: "Tipo",
} as const;

export type GlossaryKey = keyof typeof validAttributes;
